print("Hello")


*WORK PERMIT ON 21ST DECEMBER TO 31ST DECEMBER*

PYTHON:- 
CREATE A DATABASE ON STORE 100+ DATA ABOUT NAME , DOB , MO NUMBER 
THIS BASE ON APPLICATION 
 NOT ONLY CODE 

EXCELE:-
NAME WISE TO SORT A DATA TO SEARCHABLE SORT FORMULAS

*NOTE:- THIS ALL PROJECT ON COMPLETE IN 10 DAYS AFTER WE CUT YOUR SALARY AMOUNT*